# version: '3.8'
services:
  # アプリケーションのコンテナ
  app:
    image: maven:3.9.6-eclipse-temurin-17
    container_name: campass_app
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - ./backend/app:/app
      - ./backend/app/uploads:/app/uploads  # 画像アップロード用ディレクトリのマウント
      - ~/.m2:/root/.m2
    # # 本番用コマンド
    # command: >
    #   sh -c '
    #   echo "Building in progress…";
    #   mvn clean package -DskipTests;
    #   echo "Application starting…";
    #   java -jar target/app-0.0.1-SNAPSHOT.jar
    #   '
    
    # 開発用コマンド
    command: >
      sh -c '
      echo "Application starting…";
      mvn spring-boot:run
      '
    environment:
      SPRING_BOOT_DOCKER_COMPOSE_SKIP: "true"
      SPRING_BOOT_DOCKER_COMPOSE_DISABLED: "true"
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/campassdb # データベースの情報
      SPRING_DATASOURCE_USERNAME: user        # データベースのユーザー
      SPRING_DATASOURCE_PASSWORD: password    # データベースのパスワード
      SPRING_REDIS_HOST : redis   # OTP 用のサービス
    depends_on:
      db:
        condition: service_healthy
      redis: 
        condition: service_started  # redisが起動したら
    networks:
      - campass-network
  
  # データベースのコンテナ
  db:
    image: mysql:8.0
    container_name: campass_db
    ports:
      - "3306:3306"    
    environment:
      MYSQL_DATABASE: campassdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql
      - ./backend/db/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - campass-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"] 
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: "redis:7-alpine"   # redisイメージ
    container_name: redis     # Springが使うコンテナ名
    ports:
      - "6379:6379"           # ポート
    volumes:
      - redis_data:/data      # (Optional)コンテナをリスタートしてもデータを保存する
    networks:
      - campass-network

networks:
  campass-network:

volumes:
  redis_data: {}  # redisのボリューム
  mysql: